name: Build

on:
  workflow_dispatch:
    inputs:
      packageName:
        description: 'Game Package Name'
        required: true
        default: 'com.dts.freefireth'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Replace Package Name
        run: |
          sed -i 's/com.game.packagename/${{ github.event.inputs.packageName }}/g' module/src/main/cpp/game.h

      - name: Build Module
        run: |
          chmod +x gradlew
          ./gradlew :module:assembleRelease --stacktrace

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: module-${{ github.event.inputs.packageName }}
          path: module/build/outputs/apk/release/module-release.apk
